### ISSUE TITLE
ws issues on debian 10 (raspberry pi)

### ISSUE THREAD

**Issue by ghost** [brbeaird/SmartThings_SenseMonitor#16]
Upgraded debian on my raspberry pi and ran into the ws connection closed issue you warn about.  But wanted to say that upgrading Node.js to 12.19.0 resolved the issue for me.

sudo curl -sL https://deb.nodesource.com/setup_12.x | bash -
sudo apt-get install -y nodejs

**Comment by brbeaird** [comment]
Good to know - I'll make a note to update that.
