### ISSUE TITLE
SmartThings DTH isn't creating devices

### ISSUE THREAD

**Issue by ecallegari** [brbeaird/SmartThings_SenseMonitor#2]
Looks like I got everything installed and I see data is being received at the node server with the messages.  It says successfully sent data to smartthings hub however not seeing any traffic in the debug logs from the dth.  Not sure if there is something missing there.  I'm pretty sure I got the right IP address plugged in since this isn't my first rodeo with node js :)  

Anything else I can do to debug this issue?

**Comment by brbeaird** [comment]
Tracking this one here - https://community.smartthings.com/t/beta-sense-energy-monitor/133470/8
