### ISSUE TITLE
Errors in live log for Sense Energy Monitor

### ISSUE THREAD

**Issue by jeffhummel** [brbeaird/SmartThings_SenseMonitor#9]
Everything seems connected and the node.js server is sending events/devices to smartthings hub.  I get the following errors in the log:

89854cb3-6632-47ae-bc41-7307c81d0e38  9:16:21 AM: error java.lang.NullPointerException: Cannot set property '170a7e76' on null object @line 390 (doCall)
89854cb3-6632-47ae-bc41-7307c81d0e38  9:16:21 AM: debug Updating (5) Sense Devices...
89854cb3-6632-47ae-bc41-7307c81d0e38  9:16:21 AM: error java.lang.NullPointerException: Cannot set property '25c55a21' on null object @line 390 (doCall)
89854cb3-6632-47ae-bc41-7307c81d0e38  9:16:21 AM: debug Updating (5) Sense Devices...
89854cb3-6632-47ae-bc41-7307c81d0e38  9:16:21 AM: error java.lang.NullPointerException: Cannot set property '44651f66' on null object @line 390 (doCall)
89854cb3-6632-47ae-bc41-7307c81d0e38  9:16:21 AM: debug Updating (3) Sense Devices...
89854cb3-6632-47ae-bc41-7307c81d0e38  9:16:21 AM: error java.lang.NullPointerException: Cannot set property '44651f66' on null object @line 390 (doCall)
89854cb3-6632-47ae-bc41-7307c81d0e38  9:16:21 AM: debug Updating (3) Sense Devices...
89854cb3-6632-47ae-bc41-7307c81d0e38  9:15:47 AM: debug getChildDevices(true), children=0

Seems it cant create devices for some reason.  Any ideas?

**Comment by brbeaird** [comment]
Yep, I know the problem. Will fix when I can later today.

There's also a bug in the Node server where the websocket eventually stops
closing for some reason. Still working on that.

**Comment by brbeaird** [comment]
I just pushed an update to the Node server and the SmartApp that I think will fix both of those issues. Give it another shot.

**Comment by jeffhummel** [comment]
That worked perfectly!  I have some duplicates but I will clean them up.  Very nice work sir and thanks for the speedy responses!

**Comment by brbeaird** [comment]
Interesting - the duplicates should actually clean themselves up, although
if you had them from before it could take a few days for them to fall off.
